"""Office creation flow: office-assigned nickname + one-shot temp code banner.

Covers the two deltas of the office account flow:
  1. ``create_teacher`` honours an office-assigned nickname (unique, >= 2 chars)
     and falls back to the auto-generated ``teacher_<id>`` when left blank.
  2. The first login with a temp code flags the session so the landing page
     renders the "welcome + change the temp code" banner exactly once.
"""

import sqlite3

import pytest

import flask_db
from database.connection import connect
from database.schema import ensure_schema


@pytest.fixture
def db_fx(tmp_path, monkeypatch):
    db_path = tmp_path / 'nickname_code.db'
    monkeypatch.setattr(flask_db, 'DATABASE', str(db_path))

    conn = connect(str(db_path))
    with open('database/schema.sql', encoding='utf-8') as f:
        conn.executescript(f.read())
    ensure_schema(conn)
    conn.execute(
        "INSERT OR IGNORE INTO users (username, password, role, label) "
        "VALUES ('office_manager', 'x', 'faculty_affairs', 'مدير مكتب أعضاء هيئة التدريس')"
    )
    conn.execute(
        "INSERT INTO departments (name, semesters, majors, hidden, has_sections, type) "
        "VALUES ('قسم الحاسوب', 7, 8, 0, 1, 'academic')"
    )
    conn.commit()
    conn.close()
    return str(db_path)


def _svc(conn):
    from database.repositories.teacher_repository import TeacherRepository
    from database.repositories.user_repository import UserRepository
    from services.teacher_service import TeacherService
    return TeacherService(conn, TeacherRepository(conn), UserRepository(conn))


def _teacher_data(name, academic_number, username=''):
    return {
        'name': name, 'username': username, 'email': '', 'phone': '',
        'department_id': 1, 'academic_number': academic_number,
        'qualification_id': None, 'rank_id': None, 'classification_id': None,
        'national_id': '', 'contract_date': '', 'tasks': '',
    }


def test_office_custom_nickname_used_and_duplicate_rejected(db_fx):
    conn = sqlite3.connect(db_fx)
    conn.row_factory = sqlite3.Row
    svc = _svc(conn)
    creds = svc.create_teacher(
        _teacher_data('عضو أول', 'AN-N1', username='ghaliya'),
        department_ids=[1], additional_roles=None,
    )
    assert creds['username'] == 'ghaliya'
    row = conn.execute(
        'SELECT username FROM users WHERE id = '
        '(SELECT user_id FROM teachers WHERE id = ?)',
        (creds['id'],),
    ).fetchone()
    assert row['username'] == 'ghaliya'

    with pytest.raises(ValueError) as exc:
        svc.create_teacher(
            _teacher_data('عضو ثانٍ', 'AN-N2', username='ghaliya'),
            department_ids=[1], additional_roles=None,
        )
    assert 'Username' in str(exc.value)
    conn.close()


def test_empty_nickname_falls_back_to_autogenerated(db_fx):
    conn = sqlite3.connect(db_fx)
    conn.row_factory = sqlite3.Row
    svc = _svc(conn)
    creds = svc.create_teacher(
        _teacher_data('عضو تلقائي', 'AN-N3'),
        department_ids=[1], additional_roles=None,
    )
    assert creds['username'].startswith('teacher_')
    conn.close()


def test_first_temp_code_login_shows_banner_once(app_fx, db_fx):
    conn = sqlite3.connect(db_fx)
    conn.row_factory = sqlite3.Row
    svc = _svc(conn)
    creds = svc.create_teacher(
        _teacher_data('عضو برمز مؤقت', 'AN-N4', username='temp_member'),
        department_ids=[1], additional_roles=None,
    )
    conn.close()

    client = app_fx.test_client()
    with client.session_transaction() as sess:
        sess['_csrf_token'] = 'test-token'
    r = client.post('/login', data={
        'username': 'temp_member', 'password': creds['password'],
        '_csrf_token': 'test-token',
    })
    assert r.status_code == 302
    assert '/change-password' in r.headers['Location']
    with client.session_transaction() as sess:
        assert sess.get('first_login_temp_code') is True

    r2 = client.get(r.headers.get('Location'), follow_redirects=True)
    assert r2.status_code == 200
    assert 'id="current_password"' in r2.get_data(as_text=True)

    r3 = client.post('/change-password', data={
        'current_password': creds['password'],
        'new_password': 'Changed!123',
        'confirm_password': 'Changed!123',
        '_csrf_token': 'test-token',
    }, follow_redirects=True)
    assert r3.status_code == 200
    assert 'firstLoginBanner' not in r3.get_data(as_text=True)
    with client.session_transaction() as sess:
        assert sess.get('first_login_temp_code') is None