"""Navigation registry — ordered sidebar items.

Each item defines:
  key         – matches sidebar_active values in templates
  endpoint    – Flask endpoint for url_for()
  icon        – Material Symbol name
  label       – Arabic display text
  permission  – required permission string
  active_keys – list of sidebar_active values that should highlight this item

  section     – 'main' (always visible) or 'more' (collapsible hidden section)
"""

NAV_ITEMS = [
    {
        'key': 'dashboard',
        'endpoint': 'dashboard.dashboard',
        'icon': 'dashboard',
        'label': 'لوحة التحكم',
        'permission': 'dashboard.view',
        'active_keys': ['dashboard.dashboard'],
        'exclude_roles': ['exam'],
        'section': 'main',
    },
    {
        'key': 'teachers_admin',
        'endpoint': 'teachers.teachers_list',
        'icon': 'school',
        'label': 'أعضاء هيئة التدريس',
        'permission': 'teachers.manage',
        'active_keys': ['teachers'],
        'section': 'main',
    },
    {
        'key': 'faculty_reports',
        'endpoint': 'faculty_performance.member_reports',
        'icon': 'assessment',
        'label': 'تقارير الأعضاء',
        'permission': 'faculty_performance.view',
        'active_keys': ['faculty_reports'],
        'role_filter': 'faculty_affairs',
        'section': 'main',
    },
    {
        'key': 'faculty_leaves',
        'endpoint': 'faculty_performance.leaves_index',
        'icon': 'event_busy',
        'label': 'الإجازات',
        'permission': 'faculty_performance.edit_leaves',
        'active_keys': ['faculty_leaves'],
        'role_filter': 'faculty_affairs',
        'section': 'main',
    },
    {
        'key': 'courses_admin',
        'endpoint': 'courses.courses_list',
        'icon': 'menu_book',
        'label': 'المقررات الدراسية',
        'permission': 'courses.manage',
        'active_keys': ['courses'],
        'section': 'main',
    },
    {
        'key': 'courses_view',
        'endpoint': 'courses.courses_list',
        'icon': 'menu_book',
        'label': 'المقررات',
        'permission': 'courses.view',
        'active_keys': ['courses'],
        'exclude_roles': ['exam'],
        'section': 'main',
    },
    {
        'key': 'rooms',
        'endpoint': 'classrooms.rooms_list',
        'icon': 'meeting_room',
        'label': 'القاعات',
        'permission': 'rooms.view',
        'active_keys': ['rooms'],
        'section': 'main',
    },
    {
        'key': 'timetable',
        'endpoint': 'timetable.timetable',
        'icon': 'calendar_today',
        'label': 'الجدول الدراسي',
        'permission': 'timetable.view',
        'active_keys': ['timetable.timetable', 'timetable.timetable_department_view'],
        'exclude_roles': ['research_development', 'exam'],
        'section': 'main',
    },
    {
        'key': 'timetable_rnd',
        'endpoint': 'timetable.rnd_timetable',
        'icon': 'calendar_today',
        'label': 'الجدول الدراسي',
        'permission': 'timetable.view',
        'active_keys': ['timetable.rnd_timetable'],
        'role_filter': 'research_development',
        'section': 'main',
    },
    {
        'key': 'exams',
        'endpoint': 'exams.exams',
        'icon': 'grading',
        'label': 'الجدول الامتحانات',
        'permission': 'exams.view',
        'active_keys': ['exams.exams'],
        'section': 'main',
    },
    {
        'key': 'academic_calendar',
        'endpoint': 'academic_calendar.index',
        'icon': 'calendar_month',
        'label': 'الفصل الدراسي',
        'permission': 'academic_calendar.manage',
        'active_keys': ['academic_calendar'],
        'exclude_roles': ['research_development', 'exam'],
        'section': 'main',
    },
    {
        'key': 'course_content_admin',
        'endpoint': 'teacher_pages.super_admin_course_content_list',
        'icon': 'description',
        'label': 'رفع المقرر',
        'permission': 'course_content.view',
        'active_keys': ['course_content_admin'],
        'section': 'main',
    },
    {
        'key': 'course_content_teacher',
        'endpoint': 'teacher_pages.teacher_course_content',
        'icon': 'upload_file',
        'label': 'المقررات المكلف بها',
        'permission': 'course_content.edit',
        'active_keys': ['course_content'],
        'section': 'main',
    },
    {
        'key': 'history',
        'endpoint': 'history.history_list',
        'icon': 'history',
        'label': 'سجل التغييرات',
        'permission': 'history.view',
        'active_keys': ['history'],
        'section': 'more',
    },
{
        'key': 'departments',
        'endpoint': 'departments.departments_list',
        'icon': 'account_tree',
        'label': 'الأقسام',
        'permission': 'departments.manage',
        'active_keys': ['departments'],
        'section': 'more',
    },
    {
        'key': 'classroom_requests_hod',
        'endpoint': 'classroom_requests.pending',
        'icon': 'meeting_room',
        'label': 'طلبات تغيير القاعات',
        'permission': 'classroom_requests.manage',
        'active_keys': ['classroom_requests'],
        'role_filter': 'head_of_department',
        'section': 'more',
    },
    {
        'key': 'teachers_assign',
        'endpoint': 'teachers.teachers_list',
        'icon': 'person_add',
        'label': 'إضافة أستاذ للقسم',
        'permission': 'teachers.assign',
        'active_keys': ['teachers'],
        'role_filter': 'head_of_department',
        'section': 'more',
    },
    {
        'key': 'materials',
        'endpoint': 'hod_pages.hod_materials',
        'icon': 'menu_book',
        'label': 'المواد الدراسية',
        'permission': 'materials.manage',
        'active_keys': ['materials'],
        'section': 'more',
    }]
